// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQH6CdUv-z3karddHn2l9g2PiIpbLcws',
    appId: '1:748223231732:web:8ecaed777c7342e21510a1',
    messagingSenderId: '748223231732',
    projectId: 'avenger-41d91',
    authDomain: 'avenger-41d91.firebaseapp.com',
    storageBucket: 'avenger-41d91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmux0qccc4ed3aIk7A0kgJfMPcGEgCeuo',
    appId: '1:748223231732:android:989fa59cc6316dc31510a1',
    messagingSenderId: '748223231732',
    projectId: 'avenger-41d91',
    storageBucket: 'avenger-41d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAtA06WnpNojWTCvw8MByWK24Zf9hMz4',
    appId: '1:748223231732:ios:b295e7f6d8e23aea1510a1',
    messagingSenderId: '748223231732',
    projectId: 'avenger-41d91',
    storageBucket: 'avenger-41d91.appspot.com',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAtA06WnpNojWTCvw8MByWK24Zf9hMz4',
    appId: '1:748223231732:ios:d4cc8c8fa8224d2a1510a1',
    messagingSenderId: '748223231732',
    projectId: 'avenger-41d91',
    storageBucket: 'avenger-41d91.appspot.com',
    iosBundleId: 'com.example.inventory.RunnerTests',
  );
}
